#!/bin/bash
set -e
set -o pipefail

if [[ ":$PATH:" == *":$HOME/.local/bin:"* ]]; then
  echo "Your path is correctly set"
else
  echo "Your path is missing ~/.local/bin, you might want to add it."
fi

mkdir -p ~/.local/bin

curl -s -LJ https://raw.githubusercontent.com/JovianX/kubectl-kubeconfig/master/kubectl-kubeconfig --output ~/.local/bin/kubectl-kubeconfig
chmod +x ~/.local/bin/kubectl-kubeconfig

curl -s -LJ https://raw.githubusercontent.com/JovianX/kubectl-kubeconfig/master/kubectl-kubeconfig-generate --output ~/.local/bin/kubectl-kubeconfig-generate
chmod +x ~/.local/bin/kubectl-kubeconfig-generate

if [[ $# -gt 0 ]]; then
    kubectl kubeconfig generate "$@"
fi
