#!/bin/bash
set -e
set -o pipefail

HELP_TEXT="
Plugin to manipulate administrative Kubernetes configuration file.

Available subcommands:
    generate    create kubernetes file in yaml format.

Available parameters:
    --help              Print this message.
"

while test $# -gt 0; do
    case "$1" in
        (--help)
            printf "%s\n" "$HELP_TEXT"
            exit 0
            ;;
        *)
            printf '%s\n' "Unknown argument $1."
            printf "%s\n" "$HELP_TEXT"
            exit 1
            ;;
    esac
done

printf "%s\n" "$HELP_TEXT"
